# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e822ee5eb2d348fb96ef05dc1f64a3f404aacd34057bc4f14a68eefc7a15e08fc9a1c1f4198f3af173c245189794baca9c701cc66e6bc18265e1787603ff035d

test:
  secret_key_base: a96072ef19cb2f572440c4c39f46f7eb3c5c15dfc916707faf40917e443fc02a55d1aaca18ebc77d1d41243f211c7a4291bbabdf30d0d1269bb7a564cacff592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
